### ISSUE TITLE
Output Allele sequence

### ISSUE THREAD

**Issue by LYC-vio** [Maggi-Chen/DeBreak#1]
Hi,

Thank you for developing this amazing tool! 

In DeBreak paper, it said that DeBreak could keep "local sequence contents" for SV within read, and "performs local de novo assembly to reconstruct SV containing sequences" for large SVs that could not be spanned within reads. However, the vcf result uses symbolic output for REF (N) and ALT (\<DEL\>,\<INS\>, etc.) instead of nucleotide sequences.

Is there any way to make DeBreak output allele sequences?

**Comment by Maggi-Chen** [comment]
Hello,

Thank you for your interest in our tool! We are actually currently working on reporting the ALT sequences for each SV call. We should be able to update in next week or so.

Thanks,
Maggi
