### ISSUE TITLE
output dir issue

### ISSUE THREAD

**Issue by LYC-vio** [Maggi-Chen/DeBreak#3]
Seems that DeBreak directly appends the output dir before 'debreak.vcf', which will make the output vcf a hidden file (`.debreak.vcf`) when the output dir is the current dir (`.`)

**Comment by Maggi-Chen** [comment]
Hello,

Thank you for the feedback. We usually add '/' to the input --outpath if it doesn't end with '/'. It is possibly a bug that we have fixed in the latest version in GitHub. We have not updated our package in conda yet, but we will update that soon. 

Thanks,
Maggi
